/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarBottom: typeof import('./components/bar/BarBottom.vue')['default']
    BarTop: typeof import('./components/bar/BarTop.vue')['default']
    CardAnime: typeof import('./components/CardAnime.vue')['default']
    CardManga: typeof import('./components/CardManga.vue')['default']
    CardRanobe: typeof import('./components/CardRanobe.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBar: typeof import('./components/bar/TheBar.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/bar/TheInput.vue')['default']
    TheLogo: typeof import('./components/bar/TheLogo.vue')['default']
  }
}
